# Generated by Django 5.0.6 on 2024-05-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='is_gpt',
            field=models.BooleanField(default=False),
        ),
    ]
