# Generated by Django 5.0.6 on 2024-05-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='totalnaoresolvidos',
            field=models.IntegerField(default=0),
        ),
    ]
