# Generated by Django 5.0.6 on 2024-05-24 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('subject', models.TextField()),
                ('sender_object_id', models.PositiveIntegerField()),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='atendimento.conversa')),
                ('sender_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
