# Generated by Django 5.0.6 on 2024-05-16 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='sent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimento.usuario'),
        ),
    ]
