# Generated by Django 5.0.6 on 2024-05-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_stats_totalnaoresolvidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='is_avaliada',
            field=models.BooleanField(default=False),
        ),
    ]
