# Generated by Django 5.0.6 on 2024-05-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_conversa_is_gpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='bot_response_count',
            field=models.IntegerField(default=0),
        ),
    ]
