# Generated by Django 5.0.6 on 2024-05-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_alter_mensagem_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='sent',
            field=models.TextField(),
        ),
    ]
