# Generated by Django 5.0.6 on 2024-05-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0003_conversa_bot_response_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='totalresolvidosgpt',
            field=models.IntegerField(default=0),
        ),
    ]
