# Generated by Django 5.0.6 on 2024-05-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0004_remove_mensagem_sent_mensagem_sender_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='tag',
            field=models.TextField(default=9),
            preserve_default=False,
        ),
    ]
