# Generated by Django 5.0.6 on 2024-05-21 12:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0006_remove_conversa_colaboradores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
